### PR TITLE
Add support for pg_authid

### PR DESCRIPTION
**Pull request by nikkhils**
Add entries for pg_authid catalog table in all versions

### CODE REVIEW

**Comment by eeeebbbbrrrr** [comment]
These `.rs` bindings files are auto-generated (and we only store them in git to appease docs.rs builds).

Instead of hand-editing them, please add the appropriate header files to each of the `.h` files here:  https://github.com/tcdi/pgx/tree/master/pgx-pg-sys/include

**Comment by nikkhils** [comment]
@eeeebbbbrrrr that's much easier, thanks. Will re-submit. However, who will add the entries in the Rust files? Should I keep the ones I have added around or remove them in this PR and only have the .h changes?

**Comment by eeeebbbbrrrr** [comment]
It happens automatically during compilation. Like I said, those .rs files only exist to make docs.ra website happy.

**Comment by nikkhils** [comment]
@eeeebbbbrrrr great. I have re-submitted with just the header file changes

**Review by Hoverbear — APPROVED** [review]

**Comment by nikkhils** [comment]
> can you please do one other thing and update your fork from what's currently on tcdi/pgx? I screwed up our git history, and that's why this PR is showing 204 files changed.

Done!

**Comment by nikkhils** [comment]
@eeeebbbbrrrr is there anything else I need to do here? Also if everything is ok, when will this be merged into dev and when it will be part of a release? TIA.

**Review by Hoverbear — APPROVED** [review]

**Pull request merged**
