### PR TITLE
Add support for explicitly specifying SECURITY INVOKER/DEFINER functions

### LINKED ISSUE #1064: Missing possible important feature "SECURITY DEFINER" in #[pg_extern]
Why do we need it? If you have roles, and let's say you have an anonymous user to whom users will be auto-assigned until they login, and then switch to their role, the anon user may need to call the login function, which accesses private schemas, e.g. auth. Users with a read and write. While it is possible to write this function in PG UDF, it is safer to write it in rust to hide code from some DB admin.  

We can add the Security Definer by hand to the generated function but it will be good to include it in the source. Unless, I missed the process

### PR DESCRIPTION
**Pull request by JohnHVancouver**
fix #1064

Before by default functions were security invoker only. This allows specifying security invoker/definer

e.g. pg_extern(security_definer)

### CODE REVIEW

**Comment by JohnHVancouver** [comment]
Allows to explicitly specify invoker/definer. It'll error if both are specified but that doesn't seem too bad (and consistent).

```
postgres=# select proname, prosecdef from pg_proc where proname like 'hello_security%';
        proname         | prosecdef 
------------------------+-----------
 hello_security_definer | t
 hello_security_invoker | f
(2 rows)

postgres=# select hello_security_definer(), hello_security_invoker();
 hello_security_definer  | hello_security_invoker  
-------------------------+-------------------------
 Hello, security_definer | Hello, security_invoker
(1 row)
```

**Comment by eeeebbbbrrrr** [comment]
Thanks @JohnHVancouver!  Would you mind adding a test for this as well?  There's the `pgx-tests` crate.  I bet one of the existing modules would be good enough here.  I suppose the test could ensure that a function with these attributes has the proper values in `pgproc`.

**Comment by JohnHVancouver** [comment]
Added test cases

**Review by eeeebbbbrrrr — APPROVED** [review]

**Review by workingjubilee — APPROVED** [review]
Thank you!

**Pull request merged**
