### PR TITLE
Don't assume HTTPS_PROXY is HTTPS.

### PR DESCRIPTION
**Pull request by higuoxing**
cargo-pgx complains when I use it behind a proxy.

```
➜ export https_proxy=http://localhost:7890
➜ cargo pgx init
Error:
   0: Malformed proxy

Location:
   /home/v/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/cargo-pgx-0.7.2/src/command/version.rs:29

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ SPANTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   0: cargo_pgx::command::init::execute
      at /home/v/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/cargo-pgx-0.7.2/src/command/init.rs:71

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

After debugging it, I noticed that cargo-pgx assumes the HTTPS_PROXY environment variable is an HTTPS URL. Actually, HTTPS_PROXY can be assigned with an HTTP URL. This patch helps fix it.

### CODE REVIEW

**Comment by eeeebbbbrrrr** [comment]
I've fixed this PR, but in the future please note that we request PRs be made against the `develop` branch.

**Review by eeeebbbbrrrr — CHANGES_REQUESTED** [review]
This style of change looks just fine, but I wonder if we can centralize this to avoid code duplication?

Make make a new function in `src/command/mod.rs`?

**Comment by higuoxing** [comment]
> I've fixed this PR, but in the future please note that we request PRs be made against the develop branch.

Thanks, I'll keep it in mind next time I sending patches.

> This style of change looks just fine, but I wonder if we can centralize this to avoid code duplication?
> Make make a new function in src/command/mod.rs?

Good idea, but I'm not good at naming functions.

**Comment by eeeebbbbrrrr** [comment]
> Good idea, but I'm not good at naming functions.

Hahaha, you picked a fine name.  Thanks for doing that.

I just turned on CI for you, so lets make sure it passes and then I'll merge.  Welcome to the contributor club!

**Pull request merged**
