### PR TITLE
panic! at the polymorphism failure

### PR DESCRIPTION
**Pull request by Smittyvb**
Always `panic!` in the `from_datum` implementation for `AnyElement`/`AnyArray` instead of only panicking when debug assertions are enabled.

These functions should never be called anyways, so there's no real performance benefit by only panicking in debug mode.

### CODE REVIEW

**Comment by workingjubilee** [comment]
I'm surprised all our tests pass.

Can you update the documentation appropriately so people know they should **never** call these?

**Comment by Smittyvb** [comment]
I added some documentation for `Any{Element,Array}`. The documentation for them is very similar, but I figured it wasn't worth it to split the documentation into a separate file to be reused by both.

In the future it might be worth considering using a macro to generate the `any*` modules since they're almost identical, and it would allow us to support the [other polymorphic types](https://www.postgresql.org/docs/current/extend-type-system.html#EXTEND-TYPES-POLYMORPHIC) easily.

**Comment by workingjubilee** [comment]
Thank you! Yeah, I think this is good then.

**Review by workingjubilee — APPROVED** [review]
It's true that we should basically never be using `from_datum` for this and should be using `from_polymorphic_datum` always.

**Pull request merged**
