### PR TITLE
Adding post_parse_analyze hook

### PR DESCRIPTION
**Pull request by hamin**

### CODE REVIEW

**Comment by eeeebbbbrrrr** [comment]
I replied on discord with this:

> I’m on yet another road trip today but it looks like you hand-edited the bindings files. Instead, update the includes/*.h files to pull in the Postgres header with the  new symbols
>
> The bindings .rs files we keep in git are to appease docs.rs builds and are not used at all during normal compilation processes. Which is why you’re getting the undefined symbol errors

**Comment by Hoverbear** [comment]
(This PR seems abandoned, closing)

**Comment by Hoverbear** [comment]
@hamin It's no problem! :) We'd still be happy to merge when you got time to make it work via the headers as discussed. You can always ping us if you want some help.

I really hope you enjoy your vacation and get to do everything you desire on it! If you don't get back to this until after, it's ok. Relaxing comes first on vacation.

**Comment by workingjubilee** [comment]
An updated variant of this PR landed in https://github.com/tcdi/pgx/pull/800. Thank you!

**Pull request closed without merging**
