### PR TITLE
Wrap `SpinLock.*` functions in the C shim

### LINKED ISSUE #752: Consider making SpinLock methods accessible in PGX
The Postgres methods below are not accessible in PGX. Please consider adding them to pgx::pg_sys to make it easier to implement parallel scans in Index Access Methods.

- SpinLockInit
- SpinLockAcquire
- SpinLockRelease

### PR DESCRIPTION
**Pull request by thomcc**
Fixes #752.

@eeeebbbbrrrr Do we usually just expose these as `pgx_MacroNameHere` functions, or do we re-export them somewhere using the names from PG (in which case I've missed a bit)?

### CODE REVIEW

**Comment by eeeebbbbrrrr** [comment]
> Fixes #752.
> 
> @eeeebbbbrrrr Do we usually just expose these as `pgx_MacroNameHere` functions, or do we re-export them somewhere using the names from PG (in which case I've missed a bit)?

In this case I think they ought to be re-exported as their Postgres macro names.  I suppose there isn't a hard rule that we've followed.

These functions make up parts of an internal Postgres API so it seems like we should follow those names.  Other things like like "pgx_GETSTRUCT" and "pgx_list_nth", for example, really aren't used by user-facing code.

It might even make sense to make a "spin.rs" file in pgx-pg-sys/src/submodules/ and put them there.

**Comment by thomcc** [comment]
The re-exports would be pretty small so I'm not sure it makes that much sense to put in a dedicated submodule.

**Comment by eeeebbbbrrrr** [comment]
> The re-exports would be pretty small so I'm not sure it makes that much sense to put in a dedicated submodule.

I suppose what we want is for them to appear in the `pgx_pg_sys` submodule, so users would get to them via `pgx::pg_sys::SpinLockInit(...)`.

Down the road, I'd expect us to write a safe wrapper around this API, and that's probably when we should make a spin.rs submodule.

**Comment by thomcc** [comment]
> I suppose what we want is for them to appear in the `pgx_pg_sys` submodule, so users would get to them via `pgx::pg_sys::SpinLockInit(...)`.

Yeah, that's what this patch does. Everything in the `all_versions` modules gets glob-reexported, so this should allow `pgx::pg_sys::SpinLockInit(...)` as it is.

> Down the road, I'd expect us to write a safe wrapper around this API, and that's probably when we should make a spin.rs submodule.

👍

**Review by eeeebbbbrrrr — APPROVED** [review]

**Comment by osawyerr** [comment]
Hi @thomcc this doesn't appear to work (segafault)
let mutex : *mut slock_t = null_mut();
SpinLockInit(slock_t);

OS: MacOS
PGX: 0.5.6

**Comment by thomcc** [comment]
Yeah, that's not how you use it. You need to pass a pointer to a real slock_t in. See https://github.com/tcdi/pgx/blob/develop/pgx/src/spinlock.rs for an example.

**Pull request merged**
