### PR TITLE
Teach `pgx-tests/src/framework.rs` to detect `cargo test` feature arguments

### PR DESCRIPTION
**Pull request by eeeebbbbrrrr**
Running a plain `cargo test --features "a b c"` never properly worked with pgx' test framework as none of the "feature"-related arguments were being passed down into pgx' test framework.  Now they are.

In the case of a `cargo test --all --features "a b c"`-style execution, `cargo-pgx` will elide passing features to a workspace member that doesn't have that feature.

This necessitated reworking how **all** of the `cargo-pgx` commands detect which Postgres version feature flag to use, along with the general set of features to turn on.  The search order is now:

### schema/run/test/connect

- direct `cargo-pgx` argument
- `--features "pgXX"` flag
- `default = [ "pgXX" ]` from the extension's Cargo.toml

### install/package

- created from a direct `--pg_config` argument
- created from the `pg_config` on the system `$PATH`

### start/stop/status

- direct `cargo-pgx` argument
- `default = [ "pgXX" ]` from the extension's Cargo.toml

As a few drive-bys, teach cargo-pgx to output the type of `pgXX` feature flag it found and the full path to the `pg_config` binary it's using for that operation.

### CODE REVIEW

**Comment by eeeebbbbrrrr** [comment]
There's quite a bit of exact and similar code duplication that's been removed in this PR across all the various commands.  All the decision making has been moved into `crate::manifest::{get_package_manifest, pg_config_and_version}`, instead of being duplicated-ish across every-ish command.

**Comment by workingjubilee** [comment]
```yaml
    - name: create new sample extension
      run: cd /tmp/ && cargo pgx new sample

    # hack Cargo.toml to use this version of pgx from github
    - name: hack Cargo.toml
      run: |
       echo "[patch.crates-io]" >> /tmp/sample/Cargo.toml
       echo "pgx        = { path = \"${GITHUB_WORKSPACE}/pgx\"        }" >> /tmp/sample/Cargo.toml
       echo "pgx-macros = { path = \"${GITHUB_WORKSPACE}/pgx-macros\" }" >> /tmp/sample/Cargo.toml
       echo "pgx-tests  = { path = \"${GITHUB_WORKSPACE}/pgx-tests\"  }" >> /tmp/sample/Cargo.toml
    - name: show Cargo.toml
      run: cat /tmp/sample/Cargo.toml

    - name: Test sample for ${{ matrix.version }}
      run: cd /tmp/sample && cargo pgx test pg$PG_VER
```
Need to either adjust the templates used by `cargo pgx new` or adjust this CI script.

**Comment by eeeebbbbrrrr** [comment]
> Need to either adjust the templates used by cargo pgx new or adjust this CI script.

It's weird.  This doesn't happen locally.  The following works just fine:

```shell
cd /tmp
cargo pgx new sample
cd sample
cargo pgx test pg15
```

There must be a bug somewhere in the PR...

**Comment by eeeebbbbrrrr** [comment]
> There must be a bug somewhere in the PR...

Oh!  The "cargo-pgx" for this test was **only** configured with `pg15`, so it doesn't know that the default, `pg13`, is a postgres version feature flag that needs to be removed from the set, which happens here:  

https://github.com/tcdi/pgx/pull/967/files#diff-501d8223e92f9f60da2c06eb375f5284d6a76718e6e3ccae747df3ae31871c3bR87

Let me noodle this...

**Comment by eeeebbbbrrrr** [comment]
I'm pleased with this now and it'll let me finish up #958 so I'm merging.

It's dangerous to leave me to my own devices over a long holiday!

**Pull request merged**
