### PR TITLE
Add bindings for typedefs within replication/logical.h to pg_sys

### PR DESCRIPTION
**Pull request by agamble**
Specifically I'm interested in the fields of the LogicalDecodingContext struct. At the moment the struct is empty in pg_sys.

Having access to the LogicalDecodingContext allows a couple new plugin use cases around manipulating the Postgres WAL.

### CODE REVIEW

**Comment by workingjubilee** [comment]
Hello, are there any C macros in this header that you would like to use in Rust?

**Comment by Smittyvb** [comment]
This PR needs to be updated to add the bindings to `pg15.h` as well now that PostgreSQL 15 support has been added.

**Comment by workingjubilee** [comment]
No rush, it will also risk conflicting with #830 probably.

**Comment by BradyBonnette** [comment]
#830 has landed

**Comment by eeeebbbbrrrr** [comment]
Thank you!

**Pull request merged**
