### PR TITLE
Document `pg_extern(name)`

### PR DESCRIPTION
**Pull request by yrashk**
This helps with the discovery of this option.

### CODE REVIEW

**Review by thomcc — APPROVED** [review]
This looks good to me, but I'll just punt to @workingjubilee to ensure there isn't a reason this was undocumented (although that seems unlikely).

**Comment by thomcc** [comment]
Actually, it's pretty annoying to do this conditionally, since we emit uses of core::ffi::CStr/core_cstr::CStr from macros. I'd probably rather just stick with using core_cstr for another version than try to handle that conditionally (since we can't `cfg` it on that).

**Comment by thomcc** [comment]
It is still possible though, but it would definitely increase the complexity more than just accepting the dependency. So it's your call.

**Comment by thomcc** [comment]
TBH, I don't mind the core_cstr dep that much -- of these, the rayon one is the one I care about more. It's just kinda jank when we've moved CStr into libcore on its own.

**Comment by eeeebbbbrrrr** [comment]
> It is still possible though, but it would definitely increase the complexity more than just accepting the dependency. So it's your call.

fucking cstring.  Okay, lets leave it as you have it here.

**Comment by thomcc** [comment]
Oh god, all those comments were meant for another PR!

**Comment by eeeebbbbrrrr** [comment]
whee... we're in the wrong PR!

**Review by workingjubilee — APPROVED** [review]
Yeah I don't think there was a reason for this to be undocumented.

**Pull request merged**
