### PR TITLE
Added includes for "storage/spin.h"

### PR DESCRIPTION
**Pull request by osawyerr**
Added PR for https://github.com/tcdi/pgx/issues/752 - "Consider making SpinLock methods accessible in PGX".

### CODE REVIEW

**Review by thomcc — APPROVED** [review]
Looks good to me if CI comes back green.

**Comment by osawyerr** [comment]
All green

**Comment by thomcc** [comment]
A concern here that I realized is that our setjmp shim code (which we insert here and elsewhere) is not thread-safe. So I'm not really sure about this anymore.

**Comment by osawyerr** [comment]
Ok... what's the way forward with this?

**Comment by thomcc** [comment]
I'm not sure. @workingjubilee may have an idea.

**Comment by osawyerr** [comment]
Ah I see. Since this is already used elsewhere, is any greater risk of adding this PR till a permanent fix can be found?

**Comment by thomcc** [comment]
Well, these functions are explicitly *for* use in multiple threads. Which will always be (quite) unsafe. The existing ones aren't, and have a caveat in the readme to this effect (see https://github.com/tcdi/pgx#caveats--known-issues).

**Comment by osawyerr** [comment]
I thought that they were meant to be used in multiple _processes_ not multiple _threads_. Example is in **nbtree.c** in postgres.

**Comment by thomcc** [comment]
Oh, sorry, my bad. In that case these should be fine.

**Comment by eeeebbbbrrrr** [comment]
> I thought that they were meant to be used in multiple _processes_ not multiple _threads_. Example is in **nbtree.c** in postgres. Functionality we are building is intended to be used like in nbtree.c

Correct!  Postgres doesn't use threads and all its various locking primitives are designed to be cross-*process*.  So this PR is fine.  We should definitely merge it.

In fact, I'm doing that now...

**Pull request merged**
