### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by kianmeng**
Found via `codespell -S target -L
crate,inout,postgressql,nd,te,inh,larg,tthe,statics,noes,ser`

### CODE REVIEW

**Review by workingjubilee — CHANGES_REQUESTED** [review]
Please do not change any non-comment code, especially in macros.

**Review by workingjubilee — APPROVED** [review]
Excellent!

**Comment by eeeebbbbrrrr** [comment]
@kianmeng we merge PRs to our `develop` branch first.  After changing this PR to do that, there's now a handful of files that conflict.

Would you mind rebasing your PR against `develop`, then I'll be happy to merge.  Thanks a bunch!

**Comment by kianmeng** [comment]
@eeeebbbbrrrr Done. Please check if I miss out anything?

**Comment by eeeebbbbrrrr** [comment]
PR looks good.  Soon as CI passes (~25 minutes) I'll merge it.  Thanks again, @kianmeng!

**Review by eeeebbbbrrrr — APPROVED** [review]

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Pull request merged**
